apiVersion: v1
kind: Service
metadata:
  name: wil-service
spec:
  selector:
    app: wil # Matches the Deployment's selector
  ports:
  - protocol: TCP
    port: 8888 # Host port inside cluster (you can choose any available port)
    targetPort: 8888  # Maps to the container port
    nodePort: 30080
  type: NodePort
